# -*- coding: utf-8 -*-
"""Semana3_Atividade.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VFroZkApKiBBLdpD-vZADDPvMkwR88pk
"""

import numpy as np
import matplotlib.pyplot as plt
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.cluster import KMeans
from sklearn.metrics import adjusted_rand_score, accuracy_score

X, y = load_iris(return_X_y=True)
X = StandardScaler().fit_transform(X)
X_tr, X_te, y_tr, y_te = train_test_split(
    X, y, test_size=0.2, stratify=y, random_state=0)

results = {}

# ---- Supervisionado ----
for name, clf in [("Regressão Logística",
                    LogisticRegression(max_iter=500)),
                   ("KNN k=5", KNeighborsClassifier(5))]:
    clf.fit(X_tr, y_tr)
    acc = accuracy_score(y_te, clf.predict(X_te))
    cv  = cross_val_score(clf, X_tr, y_tr, cv=5).mean()
    results[name] = {"acc_test": acc, "cv5": cv}

# ---- Não-supervisionado (ARI como proxy de acurácia) ----
km = KMeans(n_clusters=3, n_init=20, random_state=0).fit(X)
ari_train = adjusted_rand_score(y, km.labels_)

# ARI no teste (rótulos do KMeans por votação majoritária)
labels_te = km.predict(X_te)
# mapeamento cluster -> classe majoritária
mapping = {}
for c in range(3):
    mask = km.labels_ == c
    if mask.sum() > 0:
        mapping[c] = np.bincount(y[mask]).argmax()
y_te_km = np.array([mapping[l] for l in labels_te])
acc_km = accuracy_score(y_te, y_te_km)
results["k-means (não-superv.)"] = {"acc_test": acc_km,
                                      "ari": ari_train}

# ---- Linha de base: prediz sempre a classe majoritária ----
majority_class = np.bincount(y_tr).argmax()
acc_base = accuracy_score(y_te, np.full_like(y_te, majority_class))
results["Linha de base (maioria)"] = {"acc_test": acc_base}

# ---- Regra de Hebb (classificador por protótipos) ----
classes = np.unique(y_tr)
prototypes = {}

# ---- "Treinamento" (calcular a média de cada classe) ----
for c in classes:
  prototypes [c] = X_tr [y_tr == c].mean(axis = 0)

# ---- Função de predição usando o produto interno ----
def hebb_predict(X):
  preds = []
  for x in X:
    scores = {c: np.dot(x, prototypes[c])for c in classes}
    preds.append(max(scores, key=scores.get))
  return np.array(preds)

# ---- Avaliação ----
y_pred_hebb = hebb_predict(X_te)
acc_hebb = accuracy_score(y_te, y_pred_hebb)

results["Hebb (correlação)"] = {"acc_test": acc_hebb}

# ---- Tabela de resultados ----
print(f"\n{'Modelo':<30} {'Acc. Teste':>12} {'CV-5':>8}")
print("-" * 55)
for name, r in results.items():
    cv_str = f"{r.get('cv5', r.get('ari', float('nan'))):.4f}"
    print(f"{name:<30} {r['acc_test']:>12.4f} {cv_str:>8}")

# ---- Gráfico de barras ----
names = list(results.keys())
accs  = [results[n]["acc_test"] for n in names]
colors = ['steelblue', 'steelblue', 'darkorange', 'gray', 'purple']
plt.figure(figsize=(9, 4))
bars = plt.bar(range(len(names)), accs, color=colors, edgecolor='white',
               linewidth=0.8)
plt.xticks(range(len(names)), names, rotation=15, ha='right', fontsize=9)
plt.ylabel("Acurácia no teste")
plt.ylim(0, 1.05)
plt.axhline(1/3, color='red', linestyle=':', label='Chance (1/3)')
plt.title("Comparação de modelos no Iris (Unidade I)")
plt.legend(fontsize=8)
for bar, acc in zip(bars, accs):
    plt.text(bar.get_x() + bar.get_width()/2, acc + 0.01,
             f"{acc:.3f}", ha='center', fontsize=8)
plt.tight_layout()
plt.savefig("u1_comparacao_modelos.pdf", dpi=150)
plt.show()