# -*- coding: utf-8 -*-
"""SEMANA4_ProjetoA

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XDAYvt1CkaE3vqV1_7SO8P-mpRiKgPNY
"""

import numpy as np
import matplotlib.pyplot as plt
from sklearn.datasets import (load_iris, load_breast_cancer,
                               make_classification)
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

class Perceptron:
    def __init__(self, eta=0.1, n_epochs=100, seed=0):
        self.eta = eta; self.n_epochs = n_epochs
        self.rng = np.random.default_rng(seed)
    def fit(self, X, y):
        n = X.shape[1]
        self.w = np.zeros(n); self.b = 0.0
        self.acc_hist = []
        for _ in range(self.n_epochs):
            for k in self.rng.permutation(len(X)):
                if y[k]*(self.w@X[k]+self.b) <= 0:
                    self.w += self.eta*y[k]*X[k]
                    self.b += self.eta*y[k]
            self.acc_hist.append(np.mean(np.sign(X@self.w+self.b)==y))
        return self

class ADALINE:
    def __init__(self, eta=0.01, n_epochs=100, seed=0):
        self.eta = eta; self.n_epochs = n_epochs
        self.rng = np.random.default_rng(seed)
    def fit(self, X, y):
        n = X.shape[1]
        self.w = np.zeros(n); self.b = 0.0
        self.acc_hist = []
        for _ in range(self.n_epochs):
            for k in self.rng.permutation(len(X)):
                e = y[k] - (self.w@X[k]+self.b)
                self.w += 2*self.eta*e*X[k]
                self.b += 2*self.eta*e
            self.acc_hist.append(np.mean(np.sign(X@self.w+self.b)==y))
        return self

# Datasets binarizados
datasets = {}
X, y = load_iris(return_X_y=True)
datasets['Iris (Sep. vs. resto)'] = (X, np.where(y==0,+1,-1))

X, y = load_breast_cancer(return_X_y=True)
datasets['Breast Cancer'] = (X, np.where(y==1,+1,-1))

for sep, name in [(2.0, 'Sintético fácil'), (0.5, 'Sintético difícil')]:
    X, y = make_classification(n_samples=200, n_features=10,
                                class_sep=sep, random_state=0)
    datasets[name] = (X, np.where(y==1,+1,-1))

fig, axes = plt.subplots(2, 2, figsize=(13, 9))
for ax, (name, (X_d, y_d)) in zip(axes.ravel(),
                                    list(datasets.items())[:4]):
    X_tr, X_te, y_tr, y_te = train_test_split(
        X_d, y_d, test_size=0.2, stratify=y_d, random_state=42)
    sc = StandardScaler().fit(X_tr)
    X_tr_s, X_te_s = sc.transform(X_tr), sc.transform(X_te)

    # Ajustar eta para ADALINE: η < 1/λ_max
    eig_max = np.linalg.eigvalsh(X_tr_s.T @ X_tr_s / len(X_tr_s)).max()

    # eta estável
    eta_ada = 0.05 / eig_max

    # eta 5x maior (para testar a instabilidade)
    eta_ada_maior = 5 * eta_ada

    perc = Perceptron(eta=0.5, n_epochs=80).fit(X_tr_s, y_tr)

    # ADALINE estável
    ada  = ADALINE(eta=eta_ada, n_epochs=80).fit(X_tr_s, y_tr)

    # ADALINE com eta maior
    ada_maior = ADALINE(eta=eta_ada_maior, n_epochs=80).fit(X_tr_s, y_tr)

    acc_te_p = np.mean(np.sign(X_te_s@perc.w+perc.b)==y_te)
    acc_te_a = np.mean(np.sign(X_te_s@ada.w+ada.b)==y_te)

    ax.plot(perc.acc_hist, 'b-', linewidth=1.5,
            label=f'Perceptron (te={acc_te_p:.3f})')
    # acurácia no teste
    acc_te_a_maior = np.mean(np.sign(X_te_s@ada_maior.w+ada_maior.b)== y_te)

    ax.plot(ada.acc_hist, 'r--', linewidth=1.5,
            label=f'ADALINE (η normal, te={acc_te_a:.3f})')

    ax.plot(ada_maior.acc_hist, 'g-.', linewidth=1.5,
            label=f'ADALINE (η maior, te={acc_te_a_maior:.3f})')

    ax.set_title(name, fontsize=10)
    ax.set_xlabel('Época'); ax.set_ylabel('Acurácia (treino)')
    ax.legend(fontsize=8); ax.set_ylim(0.4, 1.05)

plt.suptitle("Perceptron vs. ADALINE: curvas de aprendizado", y=1.01)
plt.tight_layout()
plt.savefig("u2_comparacao.pdf", dpi=150); plt.show()