# -*- coding: utf-8 -*-
"""Atividade_Semana5

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/120NffrEAxdsWJgAd83Uu1srcP4kwobsH
"""

import numpy as np
import matplotlib.pyplot as plt
from scipy.special import erfc

rng = np.random.default_rng(0)

# ============================================================
# PARÂMETROS
# ============================================================
n = 64    # dimensão
s = 8     # bits ativos (Willshaw)
p = 12     # padrões armazenados
n_trials = 50

# ============================================================
# MODELOS
# ============================================================
def store_correlation(pats_bp):
    W = pats_bp.T @ pats_bp / n
    np.fill_diagonal(W, 0); return W

def recall_correlation(W, x):
    return np.sign(W @ x)

def store_willshaw(pats_bin):
    W = np.clip(pats_bin.T @ pats_bin, 0, 1)
    np.fill_diagonal(W, 0); return W

def recall_willshaw(W, x, theta):
    return (W @ x >= theta).astype(float)

def store_ak(pats_bp, reg=1e-6):
    Rx = pats_bp.T @ pats_bp + reg * np.eye(n)
    M  = pats_bp.T @ pats_bp   # auto-associativa: X=Y
    return M @ np.linalg.inv(Rx)

def hopfield_recall(W, x, steps=20):
    for _ in range(steps):
        x_new = np.sign(W @ x); x_new[x_new==0]=1
        if np.array_equal(x_new, x): break
        x = x_new
    return x

# ============================================================
# BENCHMARK
# ============================================================
noise_levels = np.linspace(0, 0.5, 20)
models = ['Correlação', 'Willshaw', 'And.-Kohonen', 'Hopfield']
results = {m: [] for m in models}

for noise in noise_levels:
    acc = {m: [] for m in models}
    for _ in range(n_trials):
        # Padrões bipolares
        X_bp = rng.choice([-1.,1.], size=(p, n))
        # Padrões binários esparsos para Willshaw
        X_bin = np.zeros((p, n))
        for k in range(p):
            idx = rng.choice(n, s, replace=False)
            X_bin[k, idx] = 1.0

        W_corr = store_correlation(X_bp)
        W_will = store_willshaw(X_bin)
        W_ak   = store_ak(X_bp)
        W_hop  = X_bp.T @ X_bp / n; np.fill_diagonal(W_hop, 0)

        # Testar recuperação com ruído no 1º padrão
        for trial in range(p):
            # Ruído bipolar
            x_noisy = X_bp[trial].copy()
            n_flip = int(noise * n)
            flip_idx = rng.choice(n, n_flip, replace=False)
            x_noisy[flip_idx] *= -1

            x_corr = recall_correlation(W_corr, x_noisy)
            x_hop  = hopfield_recall(W_hop, x_noisy)
            x_ak   = np.sign(W_ak @ x_noisy)

            # Willshaw com ruído (inverte alguns bits ativos)
            x_noisy_bin = X_bin[trial].copy()
            x_noisy_bin[flip_idx] = 1 - x_noisy_bin[flip_idx]
            x_will = recall_willshaw(W_will, x_noisy_bin, theta=s*0.6)

            acc['Correlação'].append(np.mean(x_corr == X_bp[trial]))
            acc['Hopfield'].append(np.mean(x_hop   == X_bp[trial]))
            acc['And.-Kohonen'].append(np.mean(x_ak   == X_bp[trial]))
            acc['Willshaw'].append(np.mean(x_will  == X_bin[trial]))

    for m in models:
        results[m].append(np.mean(acc[m]))

fig, ax = plt.subplots(figsize=(9, 5))
colors = ['steelblue', 'darkorange', 'green', 'red']
linestyles = ['-', '--', '-.', ':']
for m, c, ls in zip(models, colors, linestyles):
    ax.plot(noise_levels * 100, results[m], color=c,
            linestyle=ls, linewidth=2, label=m)
ax.set_xlabel("Ruído (%)")
ax.set_ylabel("Acurácia bit média")
ax.set_title(f"Robustez ao ruído — $n={n}$, $p={p}$, $s={s}$")
ax.legend(fontsize=10); ax.grid(True, linestyle=':', alpha=0.4)
ax.set_ylim(0.4, 1.02)
plt.tight_layout()
plt.savefig("u3_benchmark_ruido.pdf", dpi=150); plt.show()